### ISSUE TITLE
changing python version

### ISSUE THREAD

**Issue by charlesfg** [cchurch/ansible-role-virtualenv#1]
@cchurch  Is there a way to explicit specify the python version or executable as I would with virtualenv -p ?

**Comment by smehan** [comment]
Role is nicely structured and I'd love to use it. I, too, need to be able to spec the python version as with 
  -p PYTHON_EXE, --python=PYTHON_EXE
                        The Python interpreter to use, e.g.,
                        --python=python2.5 will use the python2.5 interpreter
                        to create the new environment.  The default is the
                        interpreter that virtualenv was installed with
                        (/usr/bin/python)

I can put it in if you're busy, but wanted to give a shout first.

**Comment by cchurch** [comment]
I've added the feature on the [virtualenv_python branch](https://github.com/cchurch/ansible-role-virtualenv/tree/virtualenv_python), but don't yet have the tests passing, so feel free to use that as a starting point.

**Comment by cchurch** [comment]
I've added the `virtualenv_python` variable as of https://github.com/cchurch/ansible-role-virtualenv/commit/750d0c9622f430a7020629b3abaa96082cd9d8f5#diff-e17e7b2ab83078dba9ff699ca786fe47R270, and also tests to create a virtualenv using a different version of Python. Should be in the next release soon.
