### ISSUE TITLE
python3 virtualenv creation fails due to wsgiref

### ISSUE THREAD

**Issue by D4N** [cchurch/ansible-role-virtualenv#4]
I am trying to create a python3 only virtualenv with this role, which unfortunately fails due to `wsgiref`, which cannot be installed with python3.

This made me wonder: why is the wsgiref package installed by default in every virtualenv? Just to initialize the virtualenv? But that can be done just by installing any of the pre-packages. I have tried that by removing the respective part from the file `tasks/update.yml` (lines 9-17) and the role still works like a charm (for me at least).

Could the wsgiref installation be removed? If yes, I can submit a pull request.

**Comment by cchurch** [comment]
Yes, it's "installed" just to force creation of the virtualenv. Maybe using "pip" as the default package instead of "wsgiref" would work in all cases; if the virtualenv already exists, that task wouldn't do anything, otherwise it would create the virtualenv.

**Comment by D4N** [comment]
But shouldn't it be sufficient to just install the packages that the user adds to the role (either as post or pre-packages or via requirements.txt) via pip? That should also create a virtualenv if it is not present.

**Comment by tschale** [comment]
Using "pip" worked for me so far

**Comment by cchurch** [comment]
I've set the default to `pip` in https://github.com/cchurch/ansible-role-virtualenv/commit/750d0c9622f430a7020629b3abaa96082cd9d8f5#diff-393632eb02ee93f26ff815eb46193100R11 and that seems to work for my tests across Python 2 and 3. Will be included in a new release soon.
