### ISSUE TITLE
wrongly named/documented variable

### ISSUE THREAD

**Issue by tschale** [cchurch/ansible-role-virtualenv#6]
The variable is documented as `virtualenv_default_package`, but accessed as `'{{virtual_default_package|default("wsgiref")}}'` in the task `create virtualenv`

**Comment by cchurch** [comment]
![doh](https://media1.giphy.com/media/xT5LMzIK1AdZJ4cYW4/200.webp?cid=790b76115cc75ccf4f36544677c5f493&rid=200.webp)

will fix.

**Comment by cchurch** [comment]
Fixed in https://github.com/cchurch/ansible-role-virtualenv/commit/750d0c9622f430a7020629b3abaa96082cd9d8f5#diff-393632eb02ee93f26ff815eb46193100R11 -- will be in the next release happening soon.
